### ISSUE TITLE
Update to latest IDrive?

### ISSUE THREAD

**Issue by codinandhaulin** [snorre-k/idrive-docker#1]
Your docker is the only one that has worked for me on Unraid.  Could you rebuild with the latest IDrive bits?

**Comment by snorre-k** [comment]
Unfortunately I do not own an iDrive account any more. But I will have a look at the build process and try to update.
I will keep you informed.

**Comment by snorre-k** [comment]
- Good news: Updated to Idrive version 3.x in the 3.x branch. The container including the desktop service is working,
- Bad news: they completely changed the code base, the installation path and the configuration. So some upgrade steps for existing backups configurations are nessesary.
- I just created a new free 10G account, to find out, how this can be done without pain.

If you want play around, you can use the buildfile and the new compose.
I will continue tomorrow and hopefully also have a good migration path.

**Comment by codinandhaulin** [comment]
Wow - so quickly!  Thank you.
As I am new to Idrive, i don't really have upgrade/migration concerns.  What I'm most interested in is that the login persists between container restarts (and the services start up on container start).
I'm looking at your 3.x branch as a learning opportunity - Thanks again for your time and effort!

**Comment by snorre-k** [comment]
Updated to 3.x with #2 
Added some migration information, but could not really test this as I do not have a working 2.x configuration in my account.
