### ISSUE TITLE
iDrive container no longer showing online on WebUI dashboard

### ISSUE THREAD

**Issue by cybermac72** [snorre-k/idrive-docker#11]
It appears after the container upgrade from v3.4 to v3.5 (and subsequently v3.6) when logging in the container/computer is no longer registered or appears as online in the iDrive WebUI dashboard.  

As mentioned this appears to have started after the move from v3.4 to v3.5 and beyond.  I was able to try a different builder's iDrive container at v3.2 and it instantly shows the container as online, however, upgrading that container to the latest version (3.6) the container/computer reports as offline.

It seems that something has changed in the system requirements -- as if I manually initiate a backup using the iDrive at the command line within the container -- I see a error message flash on the screen that "Unable to find MAC address" before it proceeds and begins to perform the backup -- which I might add is completed successfully.  However, the container/computer continues to show as being offline from the iDrive webUI dashboard.

**Comment by cybermac72** [comment]
Hello again -- I was able to work with iDrive support to resolve the issue.  A new release of iDriveForLinux will be released shortly.  In the meantime, I have a custom package from iDrive support that corrected the issue -- the issue was definitely introduced by iDrive in the release of the v3.5 and beyond.

**Comment by cybermac72** [comment]
Are you going to continue with tagging your docker containers with the embedded version number of the iDriveForLinux version?  For example you currently have a "latest" tag and also a "3.6.0" tag for your containers on Docker Hub..  This is great as it would allow rolling back to a previous version when something like this dashboard issue occurs.  It would be greatly appreciated if you continue the trend of releasing a container tagged the version.

Again, it shouldn't go without saying "Thank You!".  It is greatly appreciated what you're doing by releasing and maintaining this iDrive container.  You have my utmost thanks and appreciation!

**Comment by snorre-k** [comment]
THX for the information.
The versioning is done automatically thanks to to work of @araines .
When a new version is released, the build is triggered and the new image gets tagged with the version and "latest".

Unfortunately I am not able to build historic versions, as they are not downloadable.

**Comment by snorre-k** [comment]
I was able to confirm the issue. Online configuration and Dashboard are not working with 3.6.0. Nevertheless local initiated backups are performed.
I will test again, when the new version is available.

**Comment by snorre-k** [comment]
I have just checked the behavior on a native installation of the iDrive agent for Linux 3.6.0 on a VM.
Here after the installation the computer becomes online in the Dashboard. After a reboot of the VM we have the same issue,

There seems to be a problem starting the dashboard service.
Maybe I can introduce a workaround - more to come.

**Comment by snorre-k** [comment]
Dashboard log in `/opt/IDriveForLinux/idriveIt/user_profile/root/user@user.com/.trace/dashboard.log` shows, that the last action the service tries to do is a network check:
`[2024-10-24 07:15:02][dashboarddaemon.py][00071]: ('Checking network connection status...',)`

an STRACE of the dashboard service start command shows, that the command `/opt/IDriveForLinux/bin/Idrivelib/dependencies/python/dashboard start` tries to ping something, but ping is not installed in the image :(

So I will include ping in the image and investigate further.

**Comment by araines** [comment]
I’ve been independently trying to fix this, but I’m currently away so hadn’t raised a PR to fix this. I’m pretty sure if you ensure ping is available on the container environment, that seems to fix it.

I did this by installing iputils-ping via apt in the docker file. Perhaps you could see if this works for you too? I’ve not had a chance to properly test that is the correct solution (ie the only required step), but I have got things working with 3.6.

**Comment by araines** [comment]
Oh I see you’ve come to the same conclusion! :)

**Comment by snorre-k** [comment]
Unfortunately that was ony one point of the issue.
With ping installed the dashboard service comes one step further, but is nevertheless shown offline in the WEB gui.

**Comment by araines** [comment]
I’m trying to think what else I did at this point. I believe I also installed ifconfig (which I think comes from net-tools), but I don’t know if that was necessary.

I did redo the account setup a number of times too, just to ensure I was properly logged in and the dashboard service was running properly.

Sorry I can’t be of much help at the moment - that’s as much as I can remember. I can take a closer look at things next week when I have access to my computer etc again.

**Comment by snorre-k** [comment]
The last error was sitting in front of the computer :)
I did not realize, that after restarting the container I had to refresh the WEB Gui Dashboard as the container hostname changed.

So I can conclude, that the missing `ping` program in the image was the root cause of the connection not being online.
@cybermac72 : Please use the new version of the image and retest your connection. If you have further issues feel free to reopen this issue.

**Comment by cybermac72** [comment]
Thank you again for the efforts.  iDrive Support, did provide me with a custom package to test that in fact does work after upgrading your original 3.6.0 container.  I suspect that iDrive has pivoted to some other means of checking connections that does not rely on PING being present.

https://www.idrive.com/idrive/sh/sh?k=p3a2h4t4l4

iDrive support has advised that a new version utilizing this method would be released shortly.

I can confirm that the new 3.6.0 container also remedies the issue.  Thank you again for all your work effort in solving this issue.
