### ISSUE TITLE
TimeZone Configuration

### ISSUE THREAD

**Issue by cybermac72** [snorre-k/idrive-docker#3]
Hello -- Thank you and great work on putting this container together with the iDrive for Linux version 3.x binary.  I wanted to share my method to effectively sync Datetime and Time Zone with the Host using the following volume mappings:

-v /etc/timezone:/etc/timezone:ro
-v /etc/localtime:/etc/localtime:ro
-v /usr/share/zoneinfo:/usr/share/zoneinfo:ro

In a future revision, it would be great to implement a TZ variable to allow setting Datetime and Time Zone.

Thank you for your consideration.  Again, fantastic work!

**Comment by cybermac72** [comment]
I also wanted to add that I created the following template for anyone using this container on Unraid (https://unraid.net/):

<Container version="2">
  <Name>iDrive</Name>
  <Repository>snorre0815/idrive-docker</Repository>
  <Registry>https://hub.docker.com/r/snorre0815/idrive-docker</Registry>
  <Network>bridge</Network>
  <Shell>bash</Shell>
  <Privileged>false</Privileged>
  <Support/>
  <Project/>
  <Overview/>
  <Category/>
  <WebUI/>
  <TemplateURL/>
  <Icon>https://static.idriveonlinebackup.com/source/images/favicon.ico</Icon>
  </ExtraParams>
  <PostArgs/>
  <DonateText/>
  <DonateLink/>
  <Requires/>
  <Config Name="Config" Target="/opt/IDriveForLinux/idriveIt" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/idrive/config</Config>
  <Config Name="Time Zone" Target="/etc/timezone" Default="" Mode="ro" Description="" Type="Path" Display="always" Required="false" Mask="false">/etc/timezone</Config>
  <Config Name="Set Time" Target="/etc/localtime" Default="" Mode="ro" Description="" Type="Path" Display="always" Required="false" Mask="false">/etc/localtime</Config>
  <Config Name="Zone Info" Target="/usr/share/zoneinfo" Default="" Mode="ro" Description="" Type="Path" Display="always" Required="false" Mask="false">/usr/share/zoneinfo</Config>
  <Config Name="Backup Path" Target="/home/backup" Default="" Mode="ro" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/user</Config>
</Container>

**Comment by snorre-k** [comment]
It was really easy to fulfill your requirement :)
Just had to add tzdata package to the image.
#5
