### ISSUE TITLE
TimeDate Issue following implementation of TZ variable

### ISSUE THREAD

**Issue by cybermac72** [snorre-k/idrive-docker#7]
I also wanted to note, as I mentioned previously of the volume mappings needed before you implemented the TZ variable.  I have noticed that although the container appears to display the correct time for the timezone when executing the date command.  I noticed that the post backup reports received from iDrive are once again in UTC whereas with the three (3) volume mappings to sync the timezone these same reports showed time in assigned timezone.

See below:

![image](https://github.com/snorre-k/idrive-docker/assets/82063746/f39f084b-2785-4f49-b5fe-a1a4d2f03110)

![image](https://github.com/snorre-k/idrive-docker/assets/82063746/73e53c3b-faa6-47a4-8c4e-da1b56998f02)

As shown in the 2nd image, the scheduled time shows correctly, but the Start and End times are in UTC.

The only difference being I removed the volume mappings I'd added to correct the timezone without the TZ variable and pulled the new image that uses TZ.

**Comment by cybermac72** [comment]
Just some additional information -- It appears that inside the container, as you'll see below -- the date/time reflect the TZ variable but "/etc/localtime" and "/etc/timezone" are still presenting UTC.

![image](https://github.com/snorre-k/idrive-docker/assets/82063746/ca606a5d-28f1-4c4b-b48b-50759f96cb2a)

**Comment by snorre-k** [comment]
@cybermac72 - THX for the information
I will have a look on that.

**Comment by snorre-k** [comment]
I think I have a solution.

I will update `/etc/localtime` link with the data from the TZ variable (if it exists) and call `dpkg-reconfigure -f noninteractive tzdata` to get the time zone configured in the container for all processes.

**Comment by snorre-k** [comment]
This seems to work. Logs:
```
Backup Scheduled Time: Fri May  3 16:42:00 2024
Backup Start Time: Fri May  3 16:42:02 2024
...

[      BACKUP TIME       ] [STATUS ] [   BACKUP  ] [ FILE NAME ] [ FILE SIZE ]
------------------------------------------------------------------------------
[Fri May  3 16:42:07 2024] [SUCCESS] [INCREMENTAL] [/source/1/root/.bash_history] [8.21 KB]
[Fri May  3 16:42:07 2024] [SUCCESS] [INCREMENTAL] [/source/1/root/.lesshst] [37 bytes]
[Fri May  3 16:42:07 2024] [SUCCESS] [INCREMENTAL] [/source/1/root/.viminfo] [13.62 KB]
[Fri May  3 16:42:07 2024] [SUCCESS] [    FULL   ] [/source/1/root/idrive-docker/.git/FETCH_HEAD] [217 bytes]
[Fri May  3 16:42:07 2024] [SUCCESS] [INCREMENTAL] [/source/1/root/idrive-docker/.git/HEAD] [23 bytes]
...
Backup End Time : Fri May  3 16:42:11 2024
```

I will make a PR.
