### ISSUE TITLE
Update to 3.4.0

### ISSUE THREAD

**Issue by araines** [snorre-k/idrive-docker#9]
Firstly, thanks for putting this together - it works a treat!  Was just hoping you might be able to run/publish with the latest version of iDrive's binaries (3.4.0): https://www.idrive.com/release-info#linux

Thanks

**Comment by snorre-k** [comment]
The auto workflow was disabled because of repo inactivity.
I have enabled it again and started a manual build:

![image](https://github.com/user-attachments/assets/7901ba85-aac5-4465-8baf-b9399a6d2f9e)
